# Generated by Django 2.0.1 on 2018-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('registration_closes', models.DateField()),
                ('theme', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('link_to_venue_map', models.CharField(max_length=200)),
                ('link_to_reg_form', models.CharField(max_length=200)),
                ('link_to_immigration_details', models.CharField(max_length=200)),
            ],
        ),
    ]
