# Generated by Django 2.0.1 on 2018-01-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visible', '0002_eventinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
