# Generated by Django 2.0.1 on 2018-01-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visible', '0003_auto_20180128_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinformation',
            options={'verbose_name': 'Event Information', 'verbose_name_plural': 'Event Information'},
        ),
    ]
