# Generated by Django 2.0.1 on 2019-03-21 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible', '0005_auto_20181216_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinformation',
            name='link_to_abstracts_form',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventinformation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eventinformation',
            name='registration_closes',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
