# Generated by Django 2.0.1 on 2018-12-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible', '0005_auto_20181216_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationguide',
            name='icon',
            field=models.CharField(default='mdi-checkbox-marked-circle-outline', max_length=200),
            preserve_default=False,
        ),
    ]
